# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  chapter-01:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme FirstDemo -sdk iphonesimulator -destination name=iphone-14-pro-max build
      working-directory: chapter01/end/FirstDemo
    - name: Run tests
      run: xcodebuild -scheme FirstDemo -sdk iphonesimulator -destination name=iphone-14-pro-max test
      working-directory: chapter01/end/FirstDemo
